server:
  port: 8080

debug: false
management.endpoints.web.exposure.include: "*"


logging:
  level:
    com.swm.mvp: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.web.client.RestTemplate: debug

spring:
  webflux:
    codec:
      max-in-memory-size=2MB:
  devtools.livereload.port: 35730
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/board?createDatabaseIfNotExist=True&useUnicode=true&characterEncoding=utf8
    username: ystc1247
    password: kj10501050
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
